package uk.co.morleydev.zander.client.data

import uk.co.morleydev.zander.client.model.arg.Project
import uk.co.morleydev.zander.client.model.arg.BuildCompiler.BuildCompiler
import uk.co.morleydev.zander.client.model.arg.BuildMode.BuildMode

/**
 * The project source build is responsible for the compilation of the project files using the makefiles
 * generated by a source prebuild
 */
trait BuildProjectSource extends ((Project, BuildCompiler, BuildMode) => Unit)
